Documenting modifying MySQL cnf file and restarting the service.
TugboatQA/docs pull request #345
Opened 2023-01-04 22:39 UTC by quicksketch

Follow-up from https://github.com/Lullabot/tugboat/issues/4666 and https://github.com/TugboatQA/images/issues/85: Document the ability to restart the MySQL service.

2023-01-04 22:45 UTC, q0rban approved these changes

2023-01-04 22:48 UTC, q0rban requested changes

2023-01-04 22:48 UTC, q0rban commented on content/reference/tugboat-images.md
> +restart the service ([which is managed using runit](/setting-up-services/how-to-set-up-services/running-a-background-process/)):
Our linter wants to make this change:

```suggestion
If MySQL or MariaDB daemon configuration needs to be changed, create or modify the configuration file and restart the
service ([which is managed using runit](/setting-up-services/how-to-set-up-services/running-a-background-process/)):
```

2023-01-05 01:24 UTC, quicksketch commented on content/reference/tugboat-images.md
> +```
```suggestion
```
Note the service restarts when the preview is committed, restarting may only be necessary when wanting the configuration
to be applied before other actions, such as importing the database.
```

2023-01-05 01:24 UTC, quicksketch commented on content/reference/tugboat-images.md
> +
```suggestion

Note the service restarts when the preview is committed, restarting may only be necessary when wanting the configuration
to be applied before other actions, such as importing the database.

```

2023-01-05 01:25 UTC, quicksketch commented
Thanks! Linter changed made and I added a sentence about how restarting is only necessary if it affects the import.

2023-01-05 19:57 UTC, q0rban approved these changes

2023-01-05 19:57 UTC, merged